/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_joinf_www_updateapkdemo_JNIUtils */

#ifndef _Included_com_joinf_www_updateapkdemo_JNIUtils
#define _Included_com_joinf_www_updateapkdemo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_joinf_www_updateapkdemo_JNIUtils
 * Method:    getHelLo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_joinf_www_updateapkdemo_JNIUtils_getHelLo
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
