/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_alexcai_javacdemo_JNIHelper */

#ifndef _Included_com_example_alexcai_javacdemo_JNIHelper
#define _Included_com_example_alexcai_javacdemo_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_alexcai_javacdemo_JNIHelper
 * Method:    stringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alexcai_javacdemo_JNIHelper_stringFromC(JNIEnv *env, jclass obj);

#ifdef __cplusplus
}
#endif
#endif
